sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t s4ki/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true s4ki/docker-react npm run test -- --coverage